use_frameworks!

platform :ios, '9.0'

target 'XKMultCornersView_Example' do
  pod 'XKMultCornersView', :path => '../'

  target 'XKMultCornersView_Tests' do
    inherit! :search_paths

    
  end
end
